[package]
name = "gen-test-fixtures"
version = "0.1.0"
edition = "2024"

[dependencies]
aes-gcm = "0.10.3"
base64 = "0.22.1"
hex = "0.4.3"
jsonwebtoken = "9.3.1"
rand = "0.8.5"
rsa = { version = "0.9.8", features = ["pem"] }
serde_json = "1.0.139"
